name: Visual Tests (Pull Request)

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-4-cores
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Project
      uses: ./.github/actions/setup
      with:
        node-version: '18'
        npm-version: '8'

    - name: Test Project
      uses: ./.github/actions/unit
      with:
        type: 'Visuals'
