name: Test (Pull Request)

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-4-cores
    steps:
    - name: Setup project
    uses: ./.github/actions/setup
    with:
      node-version: '18'
      npm-version: '8'

    - name: Test Project
    uses: ./.github/actions/unit

    - name: Test Build
      run: npm run dist
